# Generated by Django 4.1.4 on 2022-12-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
